version: "3.8"
services:
  dev:
    container_name: micro-videos-app-typescript
    build:
      context: .
      target: dev
    # ports:
    #   - "3000:3000"
    #   - "9229:9229"
    command: ./run.sh
    volumes:
      - .:/home/node/app