GET http://localhost:3200/category

###
POST http://localhost:3200/category

###
GET http://localhost:3200/category/ecb8d84d-3bac-4c23-acd6-354aa4442d9b

###
PATCH  http://localhost:3200/category/ecb8d84d-3bac-4c23-acd6-354aa4442d9b