@port = 3200

GET http://localhost:{{port}}/category

###
# @name create
@id = {{create.response.body.$.id}}
POST http://localhost:{{port}}/category
Content-Type: application/json

{
    "name": "test 123"
}


###
GET http://localhost:{{port}}/category/{{id}}

###
PUT  http://localhost:{{port}}/category/{{id}}
Content-Type: application/json

{
    "name": "test 456"
}
###
GET http://localhost:{{port}}/category/{{id}}

###
DELETE http://localhost:{{port}}/category/{{id}}